### ISSUE TITLE
Jython 2.7.0

### ISSUE THREAD

**Issue by bkahlerventer** [suvarchal/IJython#1]
Please upgrade to the latest Jython 2.7.0

**Comment by suvarchal** [comment]
Had different issues with different versions of Jython, took a small break and was testing the kernel in a sister project which uses Jython 2.7 (https://github.com/suvarchal/JyIDV). It is all working fine now, will update this project in next days.
Thanks

**Comment by domrout** [comment]
Did you ever get time to push the changes for Jython 2.7.0? It still fails for me.

**Comment by Huitzilo** [comment]
+1 here, would be great to see the 2.7 updates pushed.

**Comment by suvarchal** [comment]
soon
